### ISSUE TITLE
matrix entropy 计算方法

### ISSUE THREAD

**Issue by xiatingyu** [waltonfuture/Matrix-Entropy#5]
你好，有两个问题想请教一下作者。
第一个问题，论文里提到的entropy的计算方法是通过获取hiddenstates embedding，然后经过正则化，计算协方差矩阵，最后算出matrix entrtopy。
这里的model 用的是AutoModel，也就是用cls来得到embedding嘛？现在的llm 都是用的decoder，也就是AutoModelForCausalLM来做推理，那也就是说，这个获取到的embedding只是单纯的句子embedding和推理过程无关？那如果我想要评价一个模型的推理效果，需要先用AutoModelForCausalLM推理，然后用AutoModel计算entropy？

第二个问题是这里的entropy和通过AutoModelForCausalLM获得的logits 计算出来的entropy有什么区别呢？
```
probs = F.softmax(logits, dim=1)  
entropies = -(torch.log(probs)*probs).sum(dim=1)  
mean_entropy = torch.mean(entropies) # avg(entropy)
```
期待您的回复

**Comment by waltonfuture** [comment]
你好。我们这里没有关注推理过程，只关注模型对inputs的理解，所以我们考虑的hidden states是指语言模型最后一个mlp分类头前的hidden states（也就是最后一个transformer block的）。如果想引入到推理过程，可能需要每次生成新的token的时候重新算一次entropy。同时，torch.log是逐元素计算对数，并不是计算矩阵对数的方法。

**Comment by xiatingyu** [comment]
> entropy

``如果想引入到推理过程，可能需要每次生成新的token的时候重新算一次entropy``
那就是说，我在推理的时候一个问题对应的response有10个token，我需要计算10次entropy，获取整个句子的entropy然后取平均？

**Comment by waltonfuture** [comment]
这个我们没有验证这么计算的可行性。不过可以参考一下ppl的一些计算方式

**Comment by xiatingyu** [comment]
好的好的，谢谢您的回复
